<?php

namespace Tests\Feature;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub

    }

  /**
     * A basic feature test example.
     * @test
     * @return void
     */
    public function test_name_is_required()
    {
        $this->withoutExceptionHandling();
        //$user = factory(User::class)->make();
        $this->post('users', [
          'name' => 'John Doe'
        ]);

//        $this->assertDatabaseHas('users',[
//          'name' => 'John Doe'
//        ]);

        $this->assertDatabaseCount('users', 1);
    }
}
